B1naryStudio/asciit

app/AuthService/AuthService.php
app/Http/Controllers/API/UserController.php
app/Http/Kernel.php
app/Http/routes.php
app/Repositories/Entities/User.php
config/auth.php
resources/views/welcome.blade.php

authorisation

---

app/Http/Controllers/API/QuestionController.php
public/assets/css/style.css
public/js/models/question.js
public/js/views/question/add.js
public/js/views/templates/question/add.tpl

Fixed bugs with display errors from server and add styles for errors

Add a new question: fixed bug with validation from server

---

app/AuthService/AuthService.php
app/Http/Controllers/API/UserController.php
public/js/views/user/login.js

fix logout and changed login notification for wrong data

Logout fix

---

public/js/app.js
public/js/routes.js
public/js/views/templates/menu.tpl
public/js/views/templates/question/row.tpl

Fixed page reloading.
Cleared menu links.

hot-fix-hash-navigation - Fixed page reloading.

---

app/Http/Controllers/API/QuestionController.php
app/QuestionService/QuestionService.php
app/Repositories/Contracts/QuestionRepository.php
app/Repositories/Criteria/AnswerCriteria.php
app/Repositories/Criteria/QuestionCriteria.php
app/Repositories/Repositories/AnswerRepositoryEloquent.php
app/Repositories/Repositories/QuestionRepositoryEloquent.php
public/assets/css/style.css
public/js/controllers/question.js
public/js/models/answer.js
public/js/models/question.js
public/js/routes.js
public/js/views/answer/composite.js
public/js/views/question/collection.js
public/js/views/templates/answer/answers.tpl
public/js/views/templates/menu.tpl
public/js/views/templates/question/collection.tpl
public/js/views/templates/question/row.tpl

Added search question by keywords in title and description on the questions page.
Added criterias for Question and Answer repos.
Authorisation disabled.

Questions search

---

app/Http/routes.php
public/js/models/answer.js
public/js/models/folder.js
public/js/models/question.js
public/js/models/user.js

hot-fix-prefix-removing - Prefix 'asciit' was removed

---

app/Http/routes.php
public/js/app.js
public/js/models/answer.js
public/js/models/folder.js
public/js/models/question.js
public/js/models/user.js

Fix routing issue

---

app/Http/Controllers/API/QuestionController.php
public/index.html
public/js/views/templates/menu.tpl

Fixed bugs with select2, links in menu, title on add question

Question add title

---

public/js/controllers/question.js
public/js/models/question.js
public/js/routes.js

Added questions sorting by updated (or created) date.
Added route navigation for search.

Sorting questions

---

public/js/app.js
public/js/views/templates/menu.tpl

Navigation

---

app/Http/routes.php
public/js/app.js

Fixed bug with navigation (prefix) and menu (load several menus)

Hot fix: fixed bug with navigation and loading pages

---

public/js/controllers/user.js

Fixed bug with rendering login form

Navigation fix

---

public/assets/css/style.css
public/js/views/templates/question/row.tpl

Fixed styles with popup and fixed bug with folder name on all questions page

Hot fix: fixed styles

---

app/Http/Controllers/API/QuestionController.php
app/Services/Questions/QuestionService.php
public/js/controllers/question.js
public/js/models/question.js
public/js/views/question/collection.js
public/js/views/question/paginator.js

Pagination updated. It works with the search.
Added saving the search query in the input after the page reloading.

Pagination

---

public/js/views/templates/question/paginator.tpl

fix pagination view

---

public/js/views/templates/main-layout.tpl
public/js/views/templates/question/paginator.tpl

deleted horizontal scroll

---

public/js/controllers/question.js
public/js/views/main-layout.js
public/js/views/question/collection_layout.js
public/js/views/templates/main-layout.tpl
public/js/views/templates/question/collection-layout.tpl

fixed_pagination

---

public/assets/css/style.css
public/js/views/templates/menu.tpl

Fixed menu buttons overlapping.

Hot fix: Fixed menu buttons overlapping

---

app/Repositories/Contracts/TagRepository.php
app/Repositories/Repositories/TagRepositoryEloquent.php
app/Services/Questions/QuestionService.php

Fixed bug with add question without tags

Add tags to the question: fixed bug with create question without tags

---

app/Http/Controllers/API/Question/CommentController.php
app/Http/Requests/CommentValidatedRequest.php
app/Http/routes.php
app/Providers/RepositoryServiceProvider.php
app/Repositories/Contracts/CommentRepository.php
app/Repositories/Entities/Answer.php
app/Repositories/Entities/Comment.php
app/Repositories/Entities/Question.php
app/Repositories/Repositories/CommentRepositoryEloquent.php
app/Services/Questions/Contracts/QuestionServiceInterface.php
app/Services/Questions/QuestionService.php
database/migrations/2015_08_10_112341_comment_table.php
database/migrations/2015_08_10_112816_foreign_keys_for_table_comments.php
database/seeds/CommentForAnswerSeeder.php
database/seeds/CommentForQuestionSeeder.php
database/seeds/DatabaseSeeder.php
public/assets/css/style.css
public/js/controllers/question.js
public/js/models/comment.js
public/js/views/answer/composite.js
public/js/views/comment/composite.js
public/js/views/question/single.js
public/js/views/templates/answer/single-answer.tpl
public/js/views/templates/comment/comments.tpl
public/js/views/templates/comment/single-comment.tpl
public/js/views/templates/question/question-layout.tpl

Show comments for question and answers, add new

Comments final

---

public/assets/css/style.css
public/js/controllers/question.js
public/js/models/answer.js
public/js/views/answer/composite.js
public/js/views/question/collection_layout.js
public/js/views/templates/answer/answers.tpl
public/js/views/templates/menu.tpl
public/js/views/templates/question/collection-layout.tpl
public/js/views/templates/question/collection.tpl
public/js/views/templates/question/paginator.tpl
public/js/views/templates/question/question-layout.tpl
public/js/views/templates/question/row.tpl
public/js/views/templates/tag/collection.tpl
tests/QuestionServiceTest.php

Fix tags markup

---

app/Services/Questions/QuestionService.php

Fixed an incorrect positive answers voting bug.

hot-fix-votes: Added loose comparison to the votes calculations

---

public/js/views/tag/select.js

Fixed bug with wrong tag if choose from tag list

Hot fixes: fixed bug with tags

---

public/assets/css/style.css
public/js/app.js
public/js/controllers/question.js
public/js/routes.js
public/js/views/comment/composite.js
public/js/views/templates/main-layout.tpl

Fix bug with adding new comments to question
Added spinner

Fix comment focus

---

public/js/app.js
public/js/routes.js

remove spinner from login page

remove spinner from login page

---

public/js/controllers/question.js
public/js/views/tag/select.js

Fixed bug with add tags when one tag similar another

Hot fixes: fixed bug with add tags

---

public/js/models/related-timestamps-model.js
public/js/views/templates/answer/single-answer.tpl
public/js/views/templates/comment/single-comment.tpl
public/js/views/templates/question/question-layout.tpl
public/js/views/templates/question/row.tpl

related-time: Fixed templates

---

public/js/controllers/question.js
public/js/views/answer/collection.js

hot-fix-comments: Fixed comments displaying

---

composer.lock
tests/QuestionServiceTest.php

Updated composer.lock and tests

hit-fix-real-time-update: Updated composer.lock and tests

---

public/assets/css/style.css
public/js/views/answer/collection.js
public/js/views/question/add.js
public/js/views/templates/question/add.tpl

Added graceful degradation of inputs in the incompatible with CKEditor environments.

hot-fix-iphone-editor: Editor call wrapped in try..catch.

---

public/assets/css/style.css
public/js/views/templates/vote/votes.tpl

Removed links in votes template

hot-fix-votes-links: Removed links in votes template

---

public/js/views/templates/menu.tpl
public/js/views/templates/question/row.tpl
public/js/views/templates/tag/view-row.tpl

Corrected links. Changed answers icon.

check-links: Corrected links. Changed answers icon.

---

tests/QuestionServiceTest.php

Hot fix: fixed tests

---

public/js/controllers/folder.js
public/js/views/folder/collection.js

Hot fix folders

---

public/js/views/answer/collection.js
public/js/views/question/single.js

fix answer quotation duplicates

fix answer quotation duplicates

---

public/js/routes.js

hot-fix-spinner: Fixed multiple spinner

---

public/js/routes.js

Hot fix: fixed spinner

---

app/Http/Controllers/API/QuestionController.php
app/Services/Questions/QuestionService.php
public/assets/css/style.css
public/js/controllers/question.js
public/js/models/question.js
public/js/routes.js
public/js/validation-model.js
public/js/vendor/button_down/button_down.js
public/js/views/answer/collection.js
public/js/views/comment/collection.js
public/js/views/main-layout.js
public/js/views/templates/main-layout.tpl

Search by folder name, close "Add comment" window after comment added, button to scroll up

Search by folders

---

app/Services/Auth/AuthService.php
public/js/require-main.js

central-point-auth: hot-fix test run

---

app/Services/Auth/AuthService.php

central-point-auth: hot-fix auth_me url

---

app/Http/Controllers/API/UserController.php
public/js/views/templates/menu.tpl

Added links on authorization and to the toolbar

central-point-auth-hardcoded: Added link on authorization

---

app/Http/Controllers/API/UserController.php
public/js/views/templates/menu-unauthorized.tpl
public/js/views/templates/menu.tpl

Added a link to the binary authorization on the unauthorized menu.

central-point-auth-hardcoded: Added a link to the binary authorization.

---

app/Http/routes.php
app/Services/Auth/AuthService.php
public/js/controllers/user.js
public/js/models/user.js
public/js/views/templates/menu-unauthorized.tpl

Fixed mock. Removed debuggers.
Removed link to the external auth from the toolbar.

Central point auth

---

public/assets/css/style.css
public/js/locales/dev.json
public/js/locales/en.json
public/js/locales/ru.json
public/js/locales/uk.json
public/js/views/templates/question/collection.tpl

help information about search by tags and folders

help information about search by tags and folders

---

public/assets/css/style.css
public/js/models/tag.js
public/js/views/folder/confirm.js
public/js/views/templates/question/add.tpl

Hot fix: fixed styles for popups

---

deploy.example.sh

Added build file example for development only

Added build file example

---

app/Repositories/Entities/User.php
app/Services/Auth/AuthService.php

Added saving binary_id from token

hot-fix-auth-user-data: Added saving binary_id from token

---

public/assets/css/style.css
resources/views/menu-mockup.blade.php

Update header mockup, change styles for logout button, fixed byg with popup and styles of content

Hot fix select

---

tests/QuestionServiceTest.php

hot-fix-notification: Updated tests

---

public/js/app.js
public/js/views/tag/select.js

Hot fix: fixed bug with select

---

public/assets/css/style.css
public/js/locales/dev.json
public/js/locales/en.json
public/js/locales/ru.json
public/js/locales/uk.json
public/js/views/question/collection.js
public/js/views/templates/question/collection.tpl

Added help information popup for search

Search information

---

.env.example

Changed default setting for js path

Include elixir + gulp in build process: changed default setting for js path

---

app/Http/Controllers/Mockups/AuthController.php
app/Providers/RbacServiceProvider.php
app/Rbac/Contracts/OwnershipChecker.php
app/Rbac/Facades/Ownership.php
app/Rbac/OwnershipCheckerByRepository.php
app/Rbac/items.php
config/app.php
public/js/models/model-mixins.js

Fixed bug with deleting own entries for a regular user.

hot-fix-delete-own: Fixed deleting own entries.

---

app/Events/CommentWasUpdated.php
app/Http/Controllers/API/Question/AnswerController.php
app/Http/Controllers/API/Question/CommentController.php
app/Http/routes.php
app/Listeners/DeliveryHandlers/WebSocketHandlers/CommentUpdatingToBroadcasting.php
app/Providers/EventServiceProvider.php
app/Rbac/actions.php
app/Rbac/items.php
app/Services/Questions/QuestionService.php
database/migrations/2015_08_10_112341_comment_table.php
public/assets/css/style.css
public/js/controllers/question/single.js
public/js/models/comment.js
public/js/models/model-mixins.js
public/js/require-main.js
public/js/validation-model.js
public/js/vendor/jquery/jquery.elastic.source.antarus66fork.js
public/js/vendor/jquery/jquery.elastic.source.js
public/js/views/answer/collection.js
public/js/views/comment/collection.js
public/js/views/question/single.js
public/js/views/templates/comment/single-comment.tpl
public/js/views/view-behaviors/delete-button.js
public/js/views/view-behaviors/edit-button.js
public/js/views/view-behaviors/hiding-controls.js
public/js/views/views-mixins.js

Edit comments

---

tests/QuestionServiceTest.php

edit-question: Fixed tests

---

app/Http/routes.php

Include elixir + gulp in build process: changed path

---

public/js/views/views-mixins.js

Fixed quoting an emptitess by click.

hot-fix-quote-by-click: Fixed quoting an emptitess by click.

---

app/Services/Questions/QuestionService.php

Added deleting tags while deleting question

Tags statistics doesn't changed after the questions removing

---

public/js/vendor/ckeditor/build-config.js
public/js/vendor/ckeditor/custom-instance-settings.js
public/js/vendor/ckeditor/plugins/ajax/plugin.js
public/js/vendor/ckeditor/plugins/xml/plugin.js
public/js/views/view-behaviors/gist-snippet.js

Added ckeditor plugins ajax, xml.

third-party-code: Added ckeditor plugins ajax, xml.

---

gulpfile.js
public/assets/css/style.css
public/js/vendor/ckeditor/plugins/codewidget/dialogs/gist.js
public/js/vendor/ckeditor/plugins/codewidget/dialogs/jsfiddle.js

Updated gulp config: fixed broken styles.

hot-fix-gist: Updated gulp config

---

app/Http/Controllers/API/CodeSnippetController.php
app/Http/routes.php
gulpfile.js
public/js/vendor/ckeditor/custom-instance-settings.js
public/js/vendor/snippet-iframe/new-tab-redirector.js
resources/views/errors/gist/404.blade.php
resources/views/widgets/gist.blade.php

Fixed styles downloading (needs a check)
Added redirect to the new tab from the iframe with gist.

Third party code

---

public/js/vendor/ckeditor/plugins/linkwithpreview/dialogs/main.js

Link preview

---

public/js/vendor/ckeditor/config.js
public/js/vendor/ckeditor/custom-instance-settings.js
public/js/views/view-behaviors/iframes-height.js

Attached an iframe resize moment to onload event (needs a doublecheck on the server).

third-patry-code: Attached an iframe resize moment to onload event

---

app/Services/Preview/OEmbedPreview.php
app/Services/Preview/PreviewService.php
gulpfile.js

Removed view-mixins from the gulp tasks.

Hot fix gulp fails

---

app/Listeners/DeliveryHandlers/WebSocketHandlers/QuestionUpdatingToBroadcasting.php
app/Services/Questions/QuestionService.php
public/assets/css/style.css
public/js/controllers/question/single.js
public/js/models/model-mixins.js
public/js/views/question/single.js
public/js/views/templates/question/question-layout.tpl
public/js/views/view-behaviors/best-answer.js
public/js/views/view-behaviors/closed-question-indicator.js

Updated styles.
Added the live updating of 'closed' status.
Updated images formatting insige an answer or question.

Closing question

---

app/Http/Middleware/DetectLocale.php
public/assets/css/style.css
public/js/models/model-mixins.js
public/js/validation-model.js
public/js/views/answer/collection.js
public/js/views/templates/answer/answers.tpl
public/js/views/templates/question/row.tpl

Fixed a wrong displaying of the server on new answer saving.
Updated bet answer indication styles

Hot fix answer errors

---

gulpfile.js
public/js/controllers/user.js
public/js/models/user.js
public/js/views/menu/menu.js

Header fix

---

public/assets/css/style.css
public/js/controllers/user.js
public/js/routes.js

Added spinner displaying while login in progress

Hot fix spinner

---

gulpfile.js

Hot fix: enabled uglify for gulp

---

app/Repositories/Repositories/Repository.php
database/migrations/2015_10_09_102831_rename_role_id_column_in_users_table.php

Hot fix managing users

---

gulpfile.js

Fixed gulp tasks for a new feature

hot-fix-managing-users: Fixed gulp tasks for a new feature

---

app/Http/Controllers/API/WidgetController.php
app/Repositories/Criteria/LimitCriteria.php
app/Repositories/Criteria/RecentCriteria.php
app/Services/Notifications/NotificationService.php
app/Services/Questions/Contracts/QuestionServiceInterface.php
app/Services/Questions/QuestionService.php

Fixed bugs with widget, changed serviceType

Asciit widget -> "Recent" filter shows wrong results

---

app/Listeners/DeliveryHandlers/HttpHandlers/AnswerToHttp.php
app/Listeners/DeliveryHandlers/HttpHandlers/CommentToHttp.php
app/Listeners/DeliveryHandlers/HttpHandlers/VoteAddedToHttp.php
app/Listeners/DeliveryHandlers/HttpHandlers/VoteRemovedToHttp.php
app/Services/Notifications/NotificationService.php

Added a concatenation of prefix to the notifications URL.
Refactored a notification query sending.

Hot fix notifications url

---

README.md

Updated an installation manual for zmq

manual-zmq: Updated an installation manual for zmq

---

database/migrations/2015_10_09_153005_create_global_flag_for_role_table.php
database/migrations/2015_10_12_064907_rename_is_global_column_in_roles_table.php

Disabled some parts of migrations

Hot fix: disabled some parts of migrations

---

app/Services/Questions/QuestionService.php
public/assets/css/style.css
public/js/views/view-behaviors/best-answer.js
public/js/views/view-behaviors/closed-question-indicator.js

Hot fix modern style

---

database/seeds/RealisticDataSeeder.php

Fixed gist link
Replaced the answers of the question about Ubuntu

Hot fix seeder gist

---

public/js/views/templates/answer/row-by-user.tpl
public/js/views/templates/answer/single-answer.tpl
public/js/views/templates/comment/single-comment.tpl
public/js/views/templates/question/question-layout.tpl
public/js/views/templates/question/row-by-user.tpl
public/js/views/templates/question/row.tpl

See https://trello.com/c/ZjAbQoxz/141-avatar-doesn-t-update-from-the-profile-api
:sunglasses:

Added avatar with thumb as a fallback

---

public/js/app.js

Changed the internal login to session call on the front-end.

auth-popup: Changed the internal login to session call on the front-end.

---

app/Http/Controllers/API/UserController.php
public/assets/css/style.css
public/js/routes.js

update-menu-styles: Updated menu styles

---

public/assets/css/style.css

Updated the styles for mobile version

update-menu-styles: Updated the styles for mobile version
